version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
volumes:
  my-db: