version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: erp
      POSTGRES_USER: sutech
      POSTGRES_PASSWORD: sutecherp
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
volumes:
  postgres_data: